### ISSUE TITLE
There is no latest (4.2.5) docker image on dockerhub

### ISSUE THREAD

**Issue by kirillsalykin** [pgpool/pgpool2_on_k8s#11]
Latest image is 4.2.3.
https://hub.docker.com/r/pgpool/pgpool/tags?page=1&ordering=last_updated

**Comment by pengbo0328** [comment]
Sorry for the late update of docker images.
4.2.4 and 4.2.5 is pushed.

**Comment by kirillsalykin** [comment]
thank you for quick reaction!
