### ISSUE TITLE
PGPOOL_PARAMS_SR_CHECK_PERIOD variable doesn't work

### ISSUE THREAD

**Issue by rapidia** [pgpool/pgpool2_on_k8s#15]
I think it has fixed in https://github.com/pgpool/pgpool2_on_k8s/commit/800a6bb90412b4f639aaa0cdce15f97c842d6786 , but it seems not published to docker hub.

Would you mind if I request to publish the latest image?

**Comment by pengbo0328** [comment]
The images have been updated.
You can find the latest image from [here](https://hub.docker.com/r/pgpool/pgpool).
