### ISSUE TITLE
Why are the BACKEND_FLAG# vars hardcoded to ALLOW_TO_FAILOVER in the entrypoint?

### ISSUE THREAD

**Issue by d0x2f** [pgpool/pgpool2_on_k8s#5]
See: https://github.com/pgpool/pgpool2_on_k8s/blob/d1b6d9d2028f0cf284ac3d0cd55ae2cf76649c8c/pgpool.docker/entrypoint.sh#L8

Would you accept a pull request to simply use ALLOW_TO_FAILOVER as the default like the other vars?

Also is this repo the source of the docker images published at https://hub.docker.com/r/pgpool/pgpool ?

**Comment by pengbo0328** [comment]
Thank you. 
 PGPOOL_PARAMS_BACKEND_FLAG has been changed in HEAD of the master branch.

>  Also is this repo the source of the docker images published at https://hub.docker.com/r/pgpool/pgpool ?

Yes. I will add descriptions to the Overview page of https://hub.docker.com/r/pgpool/pgpool.
Sorry for the inconvenience.

**Comment by d0x2f** [comment]
oh excellent, thank you!

> Sorry for the inconvenience.

not at all!
