### ISSUE TITLE
No pgpool_deploy_with_mount_configmap.yaml file exists

### ISSUE THREAD

**Issue by alvibd** [pgpool/pgpool2_on_k8s#9]
I was following the documentaion, when I was trying to download the pgpool_deploy_with_mount_configmap.yaml  there was a 404 error.

**Comment by pengbo0328** [comment]
Sorry. The documentation need to be updated.

Please use the following files:
* Deploy pgpool with pgpool exporter: [pgpool-deploy-metrics.yaml](https://raw.githubusercontent.com/pgpool/pgpool2_on_k8s/master/pgpool-deploy-metrics.yaml)
* Deploy pgpool only: [pgpool-deploy.yaml](https://raw.githubusercontent.com/pgpool/pgpool2_on_k8s/master/pgpool-deploy.yaml)
* Deploy pgpool with minimal settings using environment variables: [pgpool-deploy-minimal.yaml](https://raw.githubusercontent.com/pgpool/pgpool2_on_k8s/master/pgpool-deploy-minimal.yaml)

**Comment by pengbo0328** [comment]
I have updated the [documentaion](https://github.com/pgpool/pgpool2_on_k8s/blob/master/docs/index.md)
